# -*- coding: utf-8 -*-
"""Copy of Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ekZPkoJxz9a4KKVulenHzuzeu_fsVZKv
"""

!pip install faiss

import numpy as np
import faiss
import requests
from io import StringIO
import pandas as pd

